In [2]:
import numpy as np

## Matrix

In [5]:
A = np.array([[1,3,4],[2,3,5]])
print(A)
print(A.shape)

[[1 3 4]
 [2 3 5]]
(2, 3)


In [7]:
I = np.eye(3)
I1 = np.identity(3)

print(I)
print(I1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
O = np.zeros([3,3])
print(O)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


## Transpose

In [10]:
print(A.T)

[[1 2]
 [3 3]
 [4 5]]


## Matrix Multiplication

In [11]:
A = np.vstack(v1, v2, v3)
B = np.array([[1,4,-1],[3,2,7],[2,5,5]])
print(A)


NameError: name 'v1' is not defined

In [12]:
A = np.array([[2,1,1,],[1,1,1],[1,-1,2]])
print(A)

[[ 2  1  1]
 [ 1  1  1]
 [ 1 -1  2]]


In [14]:
A.getH()

AttributeError: 'numpy.ndarray' object has no attribute 'getH'

In [15]:

def adjoint_matrix(matrix):
    n = len(matrix)
    adj_matrix = np.zeros((n, n))

    for i in range(n):
        for j in range(n):
            # Calculate the cofactor of (i, j) element
            minor_matrix = np.delete(np.delete(matrix, i, axis=0), j, axis=1)
            cofactor = ((-1) ** (i + j)) * np.linalg.det(minor_matrix)

            # Assign the cofactor to the adjoint matrix
            adj_matrix[j, i] = cofactor

    return adj_matrix

# Your matrix A
A = np.array([[2, 1, 1], [1, 1, 1], [1, -1, 2]])

# Calculate the adjoint matrix
adj_A = adjoint_matrix(A)

print("Adjoint Matrix:")
print(adj_A)

Adjoint Matrix:
[[ 3. -3.  0.]
 [-1.  3. -1.]
 [-2.  3.  1.]]
