# Vectors

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.linalg as la
import numpy.linalg as nla

In [2]:
v1= np.array([2,2,3])

In [3]:
v2=np.array([-1,2,2])

Vector Operations

In [4]:
v3=v1+v2
print(v3)

[1 4 5]


In [5]:
v4=2*v1+3*v2
print(v4)

[ 1 10 12]


Normal Form : Sq.Rt (Sum of Squares of each element)

In [6]:
v1_norm=la.norm(v1)
print(v1_norm)

4.123105625617661


In [7]:
v1_norm=np.sqrt(v1@v1)
print(v1_norm)

4.123105625617661


Dot Product : Sum of products of corresponding elements

In [8]:
v1_dot=np.dot(v1,v2)
print(v1_dot)

8


In [9]:
v2_dot= v1@v2
print(v2_dot)

8


In [10]:
v3_dot=v1.dot(v2)
print(v2_dot)

8


# Matrix

In [11]:
A=np.array([[1,3,4],[2,3,5]])
print(A)


[[1 3 4]
 [2 3 5]]


In [12]:
print("Matrix Shape :", A.shape)

Matrix Shape : (2, 3)


In [13]:
I1=np.eye(3)
print(I1)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
I2=np.identity(3)
print(I2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
O1=np.zeros([3,3])
print(O1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
print(A)
print(A.T)

[[1 3 4]
 [2 3 5]]
[[1 2]
 [3 3]
 [4 5]]


In [17]:
A=np.vstack((v1,v2,v3))
print(A)

[[ 2  2  3]
 [-1  2  2]
 [ 1  4  5]]


In [18]:
B=np.array(([1,4,-1],[3,2,7],[2,5,5]))
print(B)

[[ 1  4 -1]
 [ 3  2  7]
 [ 2  5  5]]


In [19]:
C=A@B
print(C)

[[14 27 27]
 [ 9 10 25]
 [23 37 52]]


In [20]:
C=A*B
print(C)

[[ 2  8 -3]
 [-3  4 14]
 [ 2 20 25]]


Inverse Matrix

In [21]:
B_inv=la.inv(B)
print(B_inv)

[[ 0.625  0.625 -0.75 ]
 [ 0.025 -0.175  0.25 ]
 [-0.275 -0.075  0.25 ]]


In [22]:
B_inv=nla.inv(B)
print(B_inv)

[[ 0.625  0.625 -0.75 ]
 [ 0.025 -0.175  0.25 ]
 [-0.275 -0.075  0.25 ]]



Matrix Rank

In [23]:
print("Rank of A is : ", nla.matrix_rank(A))
print("Rank of A is : ", nla.matrix_rank(B))

Rank of A is :  2
Rank of A is :  3


Linear Equations

In [24]:
A=np.array(([1,4,-1],[3,2,7],[2,5,5]))
B= np.array([2,2,3])
X=la.solve(A,B)
print(X)

[0.25 0.45 0.05]


In [25]:
import random

A = np.arange(6).reshape(2,3) + random.randint(0, 10)
print(A)


[[ 8  9 10]
 [11 12 13]]


ARG-MAX

In [26]:
np.argmax(A)

5

In [27]:
np.argmax(A, axis=0)

array([1, 1, 1])

In [28]:
np.argmax(A, axis=1)

array([2, 2])

One-Hot Encoding

One-hot encoding is a technique used in machine learning and data preprocessing to represent categorical data as binary vectors

It's commonly employed when you have categorical variables, like colors or types, that cannot be directly used in many machine learning algorithms, which require numerical inputs

In [29]:

# Sample data with a "Color" column
data = {'Color': ['Red', 'Green', 'Blue', 'Red', 'Blue']}
df = pd.DataFrame(data)

print (df)


   Color
0    Red
1  Green
2   Blue
3    Red
4   Blue


In [30]:
# Using pandas' get_dummies() function for one-hot encoding
one_hot_encoded = pd.get_dummies(df, columns=['Color'])

print(one_hot_encoded)

   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           0            1          0
2           1            0          0
3           0            0          1
4           1            0          0
